const EVENT_TYPES = {
  TEMPERATURE_WARNING: "TEMPERATURE_WARNING",
  TEMPERATURE_CRITICAL: "TEMPERATURE_CRITICAL",
  TEMPERATURE_RECOVERING: "TEMPERATURE_RECOVERING",
  TEMPERATURE_NORMAL: "TEMPERATURE_NORMAL",
};

module.exports = {
  EVENT_TYPES,
};